# Generated by Django 6.0.3 on 2026-05-19 04:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(blank=True, help_text="Client's own company name", max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('client_since', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='b2bapp.company')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.URLField(blank=True)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_orders_delivered', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('current_location', models.CharField(blank=True, help_text='Comma-separated "latitude,longitude"', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='b2bapp.company')),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='b2bapp.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='b2bapp.company')),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Card', 'Card'), ('UPI', 'UPI'), ('Credit', 'Credit / Net 30')], max_length=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='Gateway / bank transaction reference', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='b2bapp.order')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_version', models.CharField(blank=True, max_length=50)),
                ('sku_code', models.CharField(max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_manufactured', models.PositiveIntegerField(default=0)),
                ('stock_available', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='b2bapp.company')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2bapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='b2bapp.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='ReturnedOrder',
            fields=[
                ('return_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_reason', models.TextField()),
                ('return_status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Picked_Up', 'Picked Up'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='Requested', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='b2bapp.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='b2bapp.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickups', to='b2bapp.driver')),
                ('old_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='b2bapp.order')),
            ],
            options={
                'db_table': 'returned_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('return_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Other', 'Other')], default='Good', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_items', to='b2bapp.product')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2bapp.returnedorder')),
            ],
            options={
                'db_table': 'returned_item',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=10)),
                ('estimated_time', models.PositiveIntegerField(help_text='Estimated travel time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='b2bapp.company')),
            ],
            options={
                'db_table': 'route',
                'ordering': ['start_location', 'end_location'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Driver', 'Driver'), ('Client', 'Client')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='b2bapp.company')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Order', 'Order'), ('Dispatch', 'Dispatch'), ('Delay', 'Delay'), ('Tracking', 'Tracking'), ('Delivered', 'Delivered'), ('Return', 'Return')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='b2bapp.order')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='b2bapp.user')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='CREATE | UPDATE | DELETE', max_length=10)),
                ('module', models.CharField(help_text="e.g. 'order', 'shipment', 'user'", max_length=50)),
                ('reference_id', models.UUIDField(help_text='PK of the modified record')),
                ('old_value', models.TextField(blank=True, help_text='JSON snapshot of the record BEFORE the change')),
                ('new_value', models.TextField(blank=True, help_text='JSON snapshot of the record AFTER the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The actor who triggered the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='b2bapp.user')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('capacity', models.PositiveIntegerField(help_text='Max stock units this warehouse can hold')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='b2bapp.company')),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ['warehouse_name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('live_location', models.CharField(blank=True, help_text='Current "latitude,longitude" of the shipment', max_length=100)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('In_Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Returned', 'Returned')], default='Ready', max_length=15)),
                ('proof_of_delivery', models.URLField(blank=True, help_text='Pre-signed S3/GCS URL for POD image or signature')),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='b2bapp.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='b2bapp.driver')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='b2bapp.order')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='b2bapp.route')),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='b2bapp.client')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_shipments', to='b2bapp.warehouse')),
            ],
            options={
                'db_table': 'shipment',
                'ordering': ['-dispatch_time'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='b2bapp.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Positive = stock added, Negative = stock deducted')),
                ('reference_id', models.UUIDField(help_text='UUID of the Shipment, ReturnedOrder, or other source record')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='b2bapp.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='b2bapp.warehouse')),
            ],
            options={
                'db_table': 'inventory_log',
                'ordering': ['-logged_at'],
            },
        ),
    ]
