# Generated by Django 6.0.3 on 2026-05-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_since',
            field=models.DateField(auto_now_add=True),
        ),
    ]
