# Generated by Django 6.0.3 on 2026-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0002_alter_client_client_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
