# Generated by Django 6.0.4 on 2026-05-31 04:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2bapp', '0005_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique hardware device identifier for driver mobile tracking', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, help_text='Unique hardware device identifier during tracking', max_length=255, null=True)),
                ('location', models.CharField(help_text='Comma-separated "latitude,longitude"', max_length=100)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_histories', to='b2bapp.driver')),
            ],
            options={
                'db_table': 'driver_location_history',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
